#!/usr/bin/env python3
"""ecosystem_dashboard.py — 生态系统 HTML 看板生成器

每轮产出: dashboard_<round>.html
展示: 测试状态, sentinel健康, cron任务, ponytail清单, 未闭环workspace
"""
import json, os, subprocess, sys, time
from pathlib import Path
from datetime import datetime

SRC = Path(__file__).resolve().parent.parent
OUT = SRC.parent / "hermes" / "workspace" / "ecosystem-dashboard"
OUT.mkdir(parents=True, exist_ok=True)

def run(cmd, timeout=10):
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return r.stdout.strip()
    except: return ""

def get_test_status():
    # Fast scan: only run a subset of tests
    r = subprocess.run(
        [sys.executable, "-m", "pytest", 
         "tests/test_codex.py", "tests/test_signal_parser.py",
         "tests/test_bugfix_workspace_skills.py",
         "-q", "--no-header"],
        capture_output=True, text=True, timeout=30
    )
    output = r.stdout + r.stderr
    # Parse pytest summary: look for line like "37 passed, 1 warning in 2.28s"
    for line in output.split("\n"):
        stripped = line.strip()
        if stripped and "passed" in stripped and "failed" not in stripped:
            # Clean line: remove warnings count if present
            clean = stripped.rsplit(",", 1)[0] if ", 1 warning" in stripped else stripped
            return clean[:120]
        if stripped and "failed" in stripped:
            return stripped[:120]
    # Fallback: return last non-warning line
    lines = [l.strip() for l in output.split("\n") if l.strip() and "warning" not in l.lower()]
    return lines[-1][:120] if lines else f"exit={r.returncode}"

def main():
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    round_num = int(time.time())
    
    # Collect data
    test_line = get_test_status()
    sys.path.insert(0, str(Path.home() / "session-launcher" / "src"))
    from ops.sentinel import list_sentinels
    sentinel_count = len(list_sentinels())
    ponytails = run(["rg", "-n", "ponytail", "src/", "--type", "py"])
    ws_no_close = []
    for d in sorted((Path.home() / "hermes" / "workspace").iterdir()):
        if d.is_dir():
            has = any(f.name.lower().startswith(("summary", "close")) for f in d.iterdir() if f.suffix == ".md")
            if not has:
                ws_no_close.append(d.name)
    
    html = f"""<!DOCTYPE html>
<html lang="zh-CN"><head>
<meta charset="UTF-8"><title>Codex++ Ecosystem Dashboard R{round_num}</title>
<style>
body{{font-family:sans-serif;background:#0d1117;color:#c9d1d9;margin:40px;max-width:900px;margin:40px auto}}
h1{{color:#58a6ff}} h2{{color:#58a6ff;border-bottom:1px solid #30363d;padding-bottom:8px}}
.card{{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:20px;margin:16px 0}}
.good{{color:#238636}} .warn{{color:#d29922}} .bad{{color:#da3633}} .info{{color:#8b9490;font-size:12px}}
table{{width:100%;border-collapse:collapse}} td,th{{padding:8px;text-align:left;border-bottom:1px solid #30363d}}
th{{color:#8b9490}}
</style></head><body>
<h1>🚀 Codex++ 生态系统看板</h1>
<p class="info">生成: {ts} | Round #{round_num}</p>
<div class="card"><h2>🧪 测试状态</h2><p>{test_line}</p></div>
<div class="card"><h2>🖥️ 哨兵</h2><p>{sentinel_count} CCS sentinels</p></div>
<div class="card"><h2>🐴 Ponytail 待升级</h2><pre style="font-size:12px;color:#c9d1d9">{ponytails[:1500]}</pre></div>
<div class="card"><h2>📁 未闭环 Workspace ({len(ws_no_close)})</h2><table><tr><th>目录</th><th>缺</th></tr>"""
    for w in ws_no_close:
        html += f"<tr><td>{w}</td><td>SUMMARY.md</td></tr>"
    html += """</table></div>
<div class="card"><h2>⏱️ Cron</h2><pre style="font-size:12px;color:#c9d1d9">"""
    cron = run(["crontab", "-l"])
    html += cron[:800]
    html += """</pre></div>
<div class="footer info" style="margin-top:24px">Dashboard automatically generated by ecosystem_dashboard.py</div>
</body></html>"""
    
    fp = OUT / f"dashboard_r{round_num}.html"
    fp.write_text(html)
    print(f"Dashboard: {fp} ({fp.stat().st_size}B)")

if __name__ == "__main__":
    main()
